version: 0.2

phases:
    install:
        commands:
            - echo Installing yarn...
            - npm install --global yarn
            - echo Run yarn dependencies...
            - yarn
    build:
        commands:
            - echo Build started on `date`
             echo Run yarn Build started on `date` ...
            - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/CdvProject